export const POKEMON_TYPES = {
  normal: "bg-gray-400 text-black",
  fire: "bg-red-500 text-white",
  water: "bg-blue-500 text-white",
  grass: "bg-green-500 text-white",
  electric: "bg-yellow-400 text-black",
  ice: "bg-teal-200 text-black",
  fighting: "bg-orange-600 text-white",
  poison: "bg-purple-500 text-white",
  ground: "bg-yellow-700 text-white",
  flying: "bg-blue-300 text-black",
  psychic: "bg-pink-500 text-white",
  bug: "bg-green-600 text-white",
  rock: "bg-yellow-800 text-white",
  ghost: "bg-purple-800 text-white",
  dragon: "bg-indigo-700 text-white",
  dark: "bg-gray-800 text-white",
  steel: "bg-gray-500 text-black",
  fairy: "bg-pink-300 text-black",
};
